spring.application.name=TaskSphere

server.port=9090
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true

spring.datasource.url=jdbc:mysql://localhost:3306/tasksphere_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=YOUR_DB_PASSWORD

# SMTP email used for notifications and password reset
spring.mail.username=YOUR_NOTIFICATION_EMAIL@gmail.com

# Gmail App Password
spring.mail.password=YOUR_APP_PASSWORD

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL@gmail.com 
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

tasksphere.upload-dir=uploads

